# Generated by Django 4.2.7 on 2025-06-21 10:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('state', models.CharField(choices=[('cry', 'Cry'), ('hungry', 'Hungry'), ('laugh', 'laugh'), ('noise', 'noise'), ('silence', 'silence')], default='noise', max_length=10)),
                ('selected_audio_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Baby',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(default='BABY', max_length=10)),
                ('status', models.CharField(default='active', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('sensor', 'Sensor'), ('speaker', 'Speaker'), ('camera', 'Camera')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=15)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('last_ping', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='audio_analysis.baby')),
            ],
            options={
                'db_table': 'Device',
            },
        ),
        migrations.AddField(
            model_name='baby',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='audio_analysis.user'),
        ),
        migrations.CreateModel(
            name='AudioSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_chunks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('error', 'Error')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_sessions', to='audio_analysis.baby')),
            ],
            options={
                'db_table': 'AudioSession',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.UUIDField()),
                ('status', models.CharField(choices=[('cry', 'Cry'), ('hungry', 'Hungry'), ('laugh', 'laugh'), ('noise', 'noise'), ('silence', 'silence')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('audio_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audio_analysis.audiosession')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='audio_analysis.baby')),
            ],
            options={
                'db_table': 'SensorData',
                'indexes': [models.Index(fields=['baby', 'timestamp'], name='SensorData_baby_id_9b352a_idx'), models.Index(fields=['device_id', 'timestamp'], name='SensorData_device__2790be_idx'), models.Index(fields=['audio_session'], name='SensorData_audio_s_775ad0_idx'), models.Index(fields=['confidence_score'], name='SensorData_confide_fda595_idx')],
            },
        ),
    ]
